name: "TorrServer"
description: "TEST"
panel_icon: mdi:movie-play
url: "https://github.com/SiamiX/hassio-addons/tree/main/TorrServer"
version: "0.134"
slug: "torrserver"
webui: "http://[HOST]:[PORT:8090]/"
watchdog: "http://[HOST]:[PORT:8090]/"
init: false
arch: 
  - aarch64
map:
  - addon_config:rw
startup: before
ports:
  8090/tcp: 8090
